// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/nova/ana/users/slin/my_git/NOvA/numu/prod4/xsec_2019/optimize_unfolding/iteration_bootstrap/./make_spectra_from_reco_no_loop.C";

#endif
